spring.application.name=demo

# Configuración de la Base de Datos H2
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# Habilitamos la BBDD dentro del Spring
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Creamos las tablaas sin borrar los datos anteriores
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true