# ==========================================
# CONEXIÓN A LA BBDD H2 DESCARGADA (.bat o .sh)
# ==========================================
# Nos conectamos  al servidor H2 que tenemos abierto el PC
spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa # Lo llamamos sa para entrar con permisos totales
spring.datasource.password=

# Habilitamos la BBDD dentro del Spring
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Creamos las tablaas sin borrar los datos anteriores
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true